import Head from "next/head";
import Link from "next/link";

import { Eye, UserPlus } from "lucide-react";
import { ModeToggle } from "~/components/theme-toggle";
import { buttonVariants } from "~/components/ui/button";
import { inter } from "~/styles/fonts";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} flex min-h-screen antialiased`}>
        <div className="container mt-8 flex flex-col">
          <div className="flex">
            <Link href="/dashboard" className="text-3xl font-semibold">
              Dashboard
            </Link>
            <div className="ml-auto">
              <ModeToggle />
            </div>
          </div>
          <div className="mt-8 flex flex-col items-center justify-center gap-4">
            <Link
              href="/dashboard/register"
              className={buttonVariants({ size: "xl" })}
            >
              <UserPlus className="mr-2" />
              Register New Data
            </Link>
            <Link
              href="/dashboard/view"
              className={buttonVariants({ size: "xl" })}
            >
              <Eye className="mr-2" />
              View Database
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
