import Head from "next/head";
import { Input } from "~/components/ui/input";

import { inter } from "~/styles/fonts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} flex min-h-screen`}>
        <div className="container mt-8 flex flex-col">
          <p className="text-4xl font-semibold">Register a student</p>
          <div className="mt-12 flex flex-col">
            <div className="flex flex-col gap-4">
              <Input type="text" placeholder="First Name" />
              <Input type="text" placeholder="Last Name" />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
