import Head from "next/head";
import { useState } from "react";
import { ModeToggle } from "~/components/theme-toggle";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Label } from "~/components/ui/label";

import { inter } from "~/styles/fonts";

type StudentInfo = {
  firstName: string;
  lastName: string;
  studentId: string;
  studentCardId: string;
};

export default function Dashboard() {
  const [setstudentInfo, setSetstudentInfo] = useState<StudentInfo>();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} flex min-h-screen`}>
        <div className="container mt-8 flex flex-col">
          <div className="flex">
            <p className="text-3xl font-semibold">Register a student</p>
            <div className="ml-auto">
              <ModeToggle />
            </div>
          </div>
          <div className="mt-8 flex flex-col">
            <div className="flex flex-col gap-6">
              <Label htmlFor="firstName">First Name</Label>
              <Input
                id="firstName"
                type="text"
                placeholder="John"
                className="-mt-3"
              />
              <Label htmlFor="lastName">First Name</Label>
              <Input
                id="lastName"
                type="text"
                placeholder="Doe"
                className="-mt-3"
              />
              <Label htmlFor="studentId">Student ID</Label>
              <Input
                id="studentId"
                type="text"
                placeholder="c1234567"
                className="-mt-3"
              />
              <Label htmlFor="studentCardId">Student Card ID</Label>
              <Input
                id="studentCardId"
                type="text"
                placeholder="ABC123"
                className="-mt-3"
              />
              <Button className="mt-8">Register</Button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
