name: PR Validator

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    name: Validate PR title
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
